# Generated by Django 3.2.9 on 2022-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
