# Generated by Django 3.2.9 on 2022-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_object_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='value_str',
            field=models.CharField(default='666', max_length=15),
        ),
    ]
