# Generated by Django 3.2.9 on 2022-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_object_value_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(default='', max_length=30)),
                ('start', models.BigIntegerField()),
                ('ref', models.CharField(default='', max_length=30)),
                ('alt', models.CharField(default='', max_length=30)),
                ('func_refgene', models.CharField(default='', max_length=50)),
                ('filters', models.CharField(default='', max_length=30)),
                ('omim', models.CharField(default='', max_length=30)),
                ('inheritance', models.CharField(default='', max_length=30)),
                ('gnomad_genome_all', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VariantFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nope', max_length=50)),
                ('filename', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
