# Generated by Django 3.2.9 on 2022-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_variant_variantfactory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='alt',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='chr',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='filters',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='func_refgene',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gnomad_genome_all',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='inheritance',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='omim',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ref',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
